deckhouse/sds-replicated-volume

images/linstor-server/client-wrapper.sh
Add linstor advise command to allowed in wrapper
This is useful command for debug
Working advise r / m commands
=> [linstor] Add linstor advise command to allowed in wrapper.

monitoring/prometheus-rules/drbd-pv-with-incorrect-settings.yaml
Changes in alert about incorrect PV spec
Now there's some incorrect recommendations in alert
Correct alert
=> [controller] Change alert about incorrect PV spec.

docs/FAQ.md
Translate instruction for migration to our module (refer to #34)
Updates documentation to reflect the switch to the sds-drbd module.
=> Translate instruction for migration to our module (refer to #34)

monitoring/prometheus-rules/drbd-pv-with-incorrect-settings.yaml
Annotation of DRBDPVWithIncorrectSettings alert has been corrected
There is grouping problem because of incorrect annotation
Correct alerts grouping
=> [controller] Correct annotation of DRBDPVWithIncorrectSettings alert

images/semver/scripts/install, images/semver/scripts/uninstall, images/semver/werf.inc.yaml, openapi/config-values.yaml, templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml, templates/nodegroupconfiguration-drbd-install-centos-like.yaml, templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Several changes to NodeGroupConfigurations:
- Added an exception when SecureBoot is enabled (a message about the need for manual maintenance of the DRBD module).
- Checking the DRBD version using semver to avoid rebuilding DRBD if a newer version of DRBD is installed than the one in the module image.
- Added a temporary function to install software packages from embedded module images (will be replaced by built-in Deckhouse functionality).
There may be several scenarios in which cyclic rebuilding of DRBD and node rebooting can occur.
Correct DRBD version check and avoid problems while SecureBoot is enabled
=> [drbd] Apply multiple fixes in NodeGroupConfigurations

templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml, templates/nodegroupconfiguration-drbd-install-centos-like.yaml, templates/nodegroupconfiguration-drbd-install-debian-like.yaml
This PR fixes some case of incorrect dockercfg parsing, while preparing for module images pull
Now there is problem in CE version
Module images pulling works correctly
=> [controller] Fix in auth parsing and bb-rp-from-module-image-install function usage

images/sds-drbd-controller/pkg/controller/linstor_leader_test.go
Added unit-tests for the linstor-leader controller.
Tests prevent the unexpected issues.
Every test is passes.
=> [controller] Add tests to linstor_leader controller

images/sds-drbd-controller/pkg/controller/linstor_node.go
Fixed slice of nodes initialization to prevent empty nodes deletion.
Because slice of nodes was initialized with len and then actual nodes were appended to the end of the slice, it goes to errors with attempts to delete nodes with empty names.
No more error logs about  "Remove LINSTOR controller node" with empty names.
=> [controller] Fix array initialization

.werf/python-deps.yaml, hooks/lib/certificate/certificate.py, lib/python/requirements.txt
This PR fixes the hooks-related issues caused by Python module updates.
Hooks broken because of module update
Properly working hooks
=> [controller] Adapt Python hooks for Deckhouse pod's switch to Alt Linux

docs/FAQ.md, docs/FAQ_RU.md, images/linstor-server/Dockerfile, images/linstor-server/client-wrapper.sh, images/sds-drbd-controller/Dockerfile, images/sds-drbd-controller/tools/evict.sh
In this PR, we temporarily introduce the `linstor node lost` command to the list of allowed commands. Additionally, we have included the `evict.sh` script into the `sds-drbd-controller` image.
**Enhanced Maintenance Capabilities:** The `evict.sh` script simplifies the evacuation of resources, making maintenance procedures more straightforward and less disruptive.
**Cluster Integrity:** The `linstor node lost` command provides a solution for cleanly removing nodes that have been lost or decommissioned without proper pre-removal evacuation, preserving the integrity and accuracy of the cluster configuration.
- Administrators will have more effective tools for performing maintenance tasks and managing cluster configurations, particularly with nodes that need to be decommissioned or have …
=> [linstor] Add "linstor node lost" command and "evict.sh" script

monitoring/prometheus-rules/storage-class.yaml
Added nonoperational storage class alert
This is important alert to keep cluster operational
Storage class operational status monitoring
=> [monitoring] Add nonoperational storage class alert 

docs/README.md, docs/README_RU.md, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_test.go, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_watcher.go, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_watcher_test.go, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_pool_test.go, images/webhooks/src/main.go, images/webhooks/src/validators/dscValidator.go, templates/webhooks/webhook.yaml
This PR addresses the remnants of our product's old naming, `sds-drbd`, updating them to the new name, `sds-replicated-volume`. Although the instances found were not critical to the product's functionality, updating these references is crucial for maintaining consistency and avoiding confusion.
Correcting the naming after our product's rename helps eliminate discrepancies and enhances code readability. It ensures uniformity across documentation and the codebase, making the product more accessible to new users and developers.
- References in the code now reflect the product's current name, `sds-replicated-volume`.
- Improved code readability and maintainability due to consistent naming conventions.
=> [controller] Fix naming after rename

images/linstor-server/client-wrapper.sh
In this PR, we add the `linstor resource-definition delete` command to the list of allowed commands. This enhancement provides users with the capability to manually delete resources from **LINSTOR**, especially useful in scenarios where the **StorageClass's** `RECLAIMPOLICY` is set to `Retain`.
Enables user-driven resource cleanup in **LINSTOR**, crucial for managing storage efficiently when auto-deletion is bypassed by a Retain reclaim policy.
Users gain control over storage resource lifecycle, ensuring optimal utilization and management within **LINSTOR** environments.
=> [linstor] Add "linstor resource-definition delete" command

docs/FAQ.md, docs/FAQ_RU.md, images/linstor-server/client-wrapper.sh, images/sds-replicated-volume-controller/Dockerfile, images/sds-replicated-volume-controller/tools/evict.sh
This PR introduces several enhancements to the LINSTOR management capabilities:
- Adds the `linstor node lost command` and the `evict.sh` script to the `sds-replicated-volume-controller` image to support enhanced maintenance operations and ensure cluster integrity by facilitating the removal of lost or decommissioned nodes.
- Introduces the `linstor resource-definition delete` command, enabling manual deletion of resources within **LINSTOR**, particularly beneficial when the **StorageClass's** `RECLAIMPOLICY` is set to `Retain`.
- **Enhanced Maintenance and Resource Management:** The `evict.sh` script and `linstor node lost` command simplify maintenance tasks and preserve cluster configuration integrity by aiding in the removal of nodes not properly evacuated before deletion.
- …
=> [linstor] Add "linstor node lost" and "linstor resource-definition delete" commands. Add "evict.sh" script 

images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_watcher.go, monitoring/prometheus-rules/storage-class.yaml
Fix label for nonoperational storage class
Now we have false positive alert
Correct alert work
=> [monitoring] Fix label for nonoperational storage class

monitoring/prometheus-rules/storage-class.yaml
Fix in storage class is not managed through ReplicatedStorageClass alert
Now there is a misprint in alert name
Correct alert
=> [monitoring] fix storage class is not managed through ReplicatedStorageClass alert

images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
In this PR, we introduce a feature that ensures the labels on StorageClasses are correctly managed. The new functionality checks existing labels on StorageClasses and, if necessary labels are missing or have incorrect values, updates them to match our specifications. 
During the migration from the `sds-drbd` module to the `sds-replicated-volume` module, a issue was identified: existing StorageClasses retained the outdated label `storage.deckhouse.io/managed-by=sds-drbd`, and new, correct labels were not applied. This discrepancy triggers the `StorageClassIsNotManagedThroughReplicatedStorageClass` alert, indicating that these StorageClasses are not properly managed by the current controller. This PR addresses this issue by implementing label reconciliation for StorageClasses, ensuring that …
=> [controller] Add StorageClass label reconcilation

images/sds-replicated-volume-controller/pkg/controller/linstor_node.go
Signed-off-by: Viktor Kramarenko <viktor.kramarenko@flant.com>
Made the new linstor node's address based on a node's InternalIP one.
Sometimes it chooses wrong IP address for a linstor node due to hardcore index.
A new linstor node will choose the IP only from node's InternalIP type address.
=> [controller] Fix a bug with a linstor node address

images/linstor-csi/Dockerfile
This PR integrates a patch in the LINSTOR CSI driver, version `1.5.0-2-g16c206a`, specifically designed to modify the deletion process of volume definitions. This adjustment is implemented as a temporary solution to prevent node reboots that have been occurring during volume deletion, suspected to be related to an unresolved issue in DRBD 9.2. By altering the sequence of actions during volume deletion — delaying the removal of volume definitions until after all associated resources have been successfully deleted — we ensure that DRBD has completely shut down the resource, thereby avoiding the triggering condition for node reboots.
The deletion of volume definitions as an initial step in the volume removal process has been identified as a potential trigger for a bug in DRBD 9.2, leading to …
=> [linstor] Patch CSI to 1.5.0-2-g16c206a: Prevent Node Reboots on Volume Deletion

templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml, templates/nodegroupconfiguration-drbd-install-centos-like.yaml, templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Add check if /etc/modules file exists
Bashible crashes if no /etc/modules file on node
Correct bashible work
=> [bashible] Add check if /etc/modules file exists

images/linstor-server/Dockerfile, images/linstor-server/liveness-satellite.sh, templates/linstor-node/daemonset.yaml
Add satellite liveness probe
Sometimes we have problem with satellites stucks, when binary is alive, but not serving connections at all
Satellite restarts automatically if stuck
=> [linstor] Add liveness probe for linstor-node

crds/replicatedstorageclass.yaml, crds/replicatedstoragepool.yaml
Add age field for custom resource definitions.
Provides more detailed output of replicatedstoragepool & replicatedstorageclass
Age field present in i.e. kubectl get {rsp | rsc}
=> [controller] Add age field

images/linstor-csi/Dockerfile
After merging [PR #78](https://github.com/deckhouse/sds-replicated-volume/pull/78) to fix node reboots during volume deletions, we found that the CSI driver version `1.5.0-2-g16c206a` was removed by its developers as it was temporary. A new release including the necessary changes has not yet been created.
To ensure continuity and stability in our system, this PR temporarily shifts CSI driver to a specific commit `98544cadb6d111d27a86a11ec07de91b99704b82` that contains the critical fixes for the node reboot issue. This approach will be utilized until an official release incorporating these changes is available.
By directly referencing the commit that includes the fixes, we can continue to benefit from these essential changes without waiting for a official release.
- Prevention of …
=> [linstor] Patch CSI to 98544cadb6d111d27a86a11ec07de91b99704b82: Prevent Node Reboots on Volume Deletion

images/linstor-server/liveness-satellite.sh
This PR addresses an issue where an incorrect file path due to a typographical error in the liveness-satellite.sh script caused the liveness probe to always report success, regardless of the actual state of the service. By correcting the log file path, we ensure the liveness probe functions correctly and reflects the true status of the system.
The typo caused the liveness probe to fail to access the intended log file, misleadingly indicating that the service was always up and running. This fix restores the functionality of the liveness probe, which is crucial for detecting and handling service failures promptly.
- Accurate liveness probe responses based on the actual operational status of the linstor-satellite.
- Improved system reliability and automated recovery actions in case of …
=> [linstor] Fix path in liveness-satellite

crds/doc-ru-replicatedstoragepool.yaml, docs/README.md, docs/README_RU.md, docs/USAGE.md, docs/USAGE_RU.md
Actual typo `lvmVolumeGroups` and `thinPoolName` in examples
Fix https://github.com/deckhouse/sds-replicated-volume/issues/86
Correct documentation
=> [docs] Actual typo lvmVolumeGroups and thinPoolName in examples

images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher.go, images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher_test.go
Add a logic to consider the Linstor's node AutoplaceTarget property for selecting Tie-breaker node.
If node is evacuating, the controller won't select it as a Tie-breaker node. 
The controller will not select the nodes with a property 'AutoplaceTarget' with 'false' value.
=> [controller] Add a check for a Linstor node's AutoplaceTarget property

templates/linstor-csi/controller.yaml, templates/linstor-node/daemonset.yaml
We have incorrect VPA for some of satellite containers, and have no VPA for linstor-resources-cleaner
We have satellite daemonset rollout because of incorrect VPA for satellite
Correct VPA for node satellite
=> Fix linstor satellite VPA

monitoring/grafana-dashboards/storage/linstor_drbd.json
Change interval_sx3 and interval_sx4 to rate_interval in grafana dashboard
We use obsolete directives interval_sx3 and interval_sx4 in dashboard. It isn't compatible with Grafana 10, so we change in to rate_interval
Proper directives in grafana dashboard
=> [monitoring] change interval_sx3 and interval_sx4 to rate_interval in grafana dashboard

templates/linstor-scheduler/configmap.yaml
Fix KubeSchedulerConfiguration API version
kubescheduler.config.k8s.io/v1beta3 is removed in k8s 1.29, so kubescheduler can't be launched
Working kubescheduler on k8s 1.29
=> [linstor] Fix KubeSchedulerConfiguration API version

monitoring/prometheus-rules/drbd-devices.yaml
Added D8DrbdPeerDeviceIsOutOfSync alert description
There is possible problems with DRBD volumes, that can be solved manually
Course of action in case of DRBD volumes out of sync
=> [monitoring] Add D8DrbdPeerDeviceIsOutOfSync alert description

images/linstor-server/client-wrapper.sh
Allow resorce-definition list-properties command in wrapper
In some cases, the user must see properties for the resource definition.
Allowed resource-definition list-properties command
=> [linstor] Allow resorce-definition list-properties

images/sds-replicated-volume-controller/tools/evict.sh
This PR enhances the `evict.sh` script by adding logging to file and introducing additional validation to check the number of diskful replicas:
- When the script is run with the `--delete-resources-only` flag, it validates the diskful replicas of the resources being deleted.
- When the script is run with the `--delete-node` flag, it validates the diskful replicas of all resources on the node being deleted.
Improved logging provides better visibility into the execution of the `evict.sh` script, making it easier to debug and audit operations. The additional validations ensure that we maintain the desired number of diskful replicas, preventing potential data loss or unavailability issues.
- Enhanced logging for better traceability and debugging.
- Increased reliability and safety in resource …
=> [controller] Improve evict.sh logging and add diskful replicas count validations

images/linstor-server/client-wrapper.sh
Allow create/delete commands for resource/storage-pool/resource-definition/node
In situations with broken nodes/resources we need possibility to create/delete some resources
Ability to repair broken resources
=> [linstor] Allow dangerous commands in wrapper

images/linstor-server/client-wrapper.sh
Fix client-wrapper script.
Exclude an internal key from linstor command.
Working `--yes-i-am-sane-and-i-understand-what-i-am-doing` key.
=> [linstor] Update client-wrapper.sh

images/sds-replicated-volume-controller/tools/replicas_manager.sh
This PR introduces a new script, `replicas_manager.sh`. The script is designed to manage and automate tasks related to LINSTOR replicas.
The `replicas_manager.sh` script simplifies the management of Linstor replicas by automating common tasks. Specifically, it checks the number of diskful replicas for each resource and, if there are fewer than required, creates the necessary number of additional diskful replicas.
=> [linstor] Add script replicas_manager.sh

images/linstor-server/client-wrapper.sh
Add `resource activate/deactivate` to allowed commands.
This is needed to recover from possible disk outages.
Command `resource activate/deactivate` can be used by users.
=> [linstor] Add "resource activate/deactivate" to allowed commands in client-wrapper.sh script

.gitignore, docs/CONFIGURATION.md, docs/CONFIGURATION_RU.md, docs/CR.md, docs/CR_RU.md, docs/FAQ.md, docs/FAQ_RU.md, docs/LAYOUTS.md, docs/LAYOUTS_RU.md, docs/README.md, docs/README_RU.md, docs/USAGE.md, docs/USAGE_RU.md
Change the module status from `experimental` to `deprecated`.
We change the name of the module to `sds-replicated-volume`. 
The status of the module in the documentation is `deprecated `.
=> [docs] Change the DRBD module status to `deprecated`

monitoring/prometheus-rules/drbd-devices.yaml
This PR corrects the namespace in the description of the D8DrbdPeerDeviceIsOutOfSync alert. The previous namespace was incorrect, causing confusion during monitoring and alerting processes.
The main goal of this change is to ensure the accuracy of alert descriptions, which is crucial for effective monitoring and quick issue resolution. By fixing the namespace in the D8DrbdPeerDeviceIsOutOfSync alert description, we eliminate potential confusion and improve the clarity of alerts.
After applying these changes, the description of the D8DrbdPeerDeviceIsOutOfSync alert will reflect the correct namespace. There should be no more confusion regarding the source of this alert, leading to more efficient monitoring and troubleshooting.
=> [monitoring] Fix namespace in `D8DrbdPeerDeviceIsOutOfSync` alert description

images/sds-replicated-volume-controller/Dockerfile, images/sds-replicated-volume-controller/pkg/controller/linstor_node.go, images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher.go, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_test.go, monitoring/prometheus-rules/replicated-pv-with-incorrect-settings.yaml
This PR adds the `quorum-minimum-redundancy` parameter set to 2 in the storage class when `replication=ConsistencyAndAvailability` (which creates PVs with 3 diskful replicas).
The `quorum-minimum-redundancy` parameter ensures that a volume can maintain quorum with a minimum number of redundant replicas. This is crucial for data consistency and availability in DRBD clusters. Setting it to 2 guarantees that the system can tolerate the failure of one node while still maintaining data integrity.
- The `quorum-minimum-redundancy` parameter is set to 2 in the storage class for `ConsistencyAndAvailability`.
- The setting is applied in LINSTOR and verified for each PV.
- If the setting cannot be applied, an alert `ReplicatedPVWithIncorrectQuorumMinimumRedundancy` is triggered.
- For LVM thick …
=> [controller] Add `quorum-minimum-redundancy` for `ConsistencyAndAvailability` ReplicatedStorageClass

images/sds-replicated-volume-controller/tools/evict.sh, images/sds-replicated-volume-controller/tools/replicas_manager.sh
This PR modifies the logic of the `replicas_manager.sh` script. Previously, the data for the `RESOURCE_AND_GROUP_NAMES` variable (which stores the mapping of resource names to their resource groups) was fetched in a single request from LINSTOR. With a large number of resources, LINSTOR returned an error. Now, multiple requests are made, each fetching data for 10 resources at a time.
Fetching data for a large number of resources in a single request from LINSTOR caused errors due to the excessive load. By batching the requests to handle 10 resources at a time, we reduce the load on LINSTOR, preventing errors and ensuring reliable operation of the `replicas_manager.sh` script.
- The `replicas_manager.sh` script will be able to handle a large number of resources without encountering errors.
- …
=> [linstor] Improve efficiency of replicas_manager.sh by batching resource queries

hooks/migrate_sdsdrbd_crds.py
Now we have errors in logs if no drbdreplicatedpools and no drbdreplicatedclasses in cluster, that worries users
This patch fixes this errors in logs
No such errors in logs
=> [internal] Fix migration hook

templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml, templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Fix DRBD build on ALT Linux and Ubuntu with kernel 6.5
We have problems with ALT Linux and Ubuntu with kernel v6.5
Correct DRBD build
=> [DRBD] Fix DRBD build on ALT Linux and Ubuntu with kernel 6.5

images/linstor-server/client-wrapper.sh, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_pool.go, images/webhooks/src/handlers/rspValidator.go, images/webhooks/src/main.go, monitoring/prometheus-rules/linstor-storage-pools.yaml
Restrict pool creation on ephemeral nodes
In case of storage pool exists on CloudEphemeral node, it can lead data loss
Restricted CloudEphemeral diskful storage pool usage
=> [controller] Restrict pool creation on ephemeral nodes

images/sds-replicated-volume-controller/tools/evict.sh
This PR improves the `evict.sh` script by improving logging and incorporating scaling operations for the `sds-replicated-volume-controller`. Specifically, the controller is scaled down to 0 replicas after performing a database backup at the beginning of the script and scaled back up to its previous replica count at the end. Additionally, before deleting resources, the script now outputs the full list of resources to be deleted and requests confirmation.
Scaling down the `sds-replicated-volume-controller` prevents it from interfering with the eviction process by creating tie breakers. This ensures that the eviction logic within the script can operate without conflicts, maintaining the integrity and correctness of the resource eviction process. The improved logging and confirmation step …
=> [controller] Enhance evict.sh logging and manage sds-replicated-volume-controller during eviction

docs/README.md, docs/README_RU.md
In [docs](https://deckhouse.io/modules/sds-replicated-volume/stable/#enabling-modules) `kubectl get mc` dont have `Ready` status, maybe need to `kubectl get module`
=> [docs] Fix check module installed status

templates/linstor-node/configmap-linstor-node-monitoring.yaml, templates/linstor-node/daemonset.yaml, templates/linstor-node/podmonitor.yaml
Change linstor satellite metrics port
We need to move used hostNetwork ports to 4200-4299 TCP range
=> [monitoring] Change linstor satellite metrics port

images/webhooks/src/handlers/rspValidator.go
Fix enableThinProvisioning value patch
No problem in webhook
=> [controller] Fix enableThinProvisioning value patch

hooks/migrate_csi_endpoint.sh, hooks/migrate_csi_endpoint_check.sh
This PR fixes the migration hook responsible for transitioning from `linstor.csi.linbit.com` CSI provisioner name to `replicated.csi.storage.deckhouse.io`. Initially, the hook attempted to create a `csi-migration-completed` secret upon successful migration. However, if the namespace for the module was not yet created (since the hook runs `beforeHelm`), the hook would fail. The creation of the secret has now been moved to a separate hook that runs `afterHelm`, checking if the migration was successful before creating the secret.
The previous implementation could fail if the namespace did not exist when the `beforeHelm` hook was executed. By moving the secret creation to an `afterHelm` hook, we ensure that the namespace is present, thus preventing the hook from failing and ensuring a smooth …
=> [controller] Fix csi migration hook

hooks/migrate_csi_endpoint.sh
This PR enhances the migration hook by adding two checks:
1. **PVC Existence Check**: Before performing migration operations, the hook now verifies the existence of a corresponding PVC for each PV. Previously, if a PV existed without a PVC (e.g., when `RECLAIMPOLICY=retain`), the hook would fail. This update ensures that operations are skipped when the PVC is absent, preventing errors.
2. **Terminating PV Check**: The hook now checks for PVs in a terminating state with the migrating provisioner. If such PVs are found, the hook will terminate with an error, avoiding potential issues.
The previous implementation could fail in scenarios where a PV existed without a PVC, especially when `RECLAIMPOLICY=retain` was set. Moreover, handling terminating PVs was insufficient, leading to possible …
=> [controller] Improve migration hook with checks for existence of PVCs and terminating PVs

hooks/migrate_csi_endpoint.sh, templates/linstor-csi/csidriver.yaml, templates/nodegroupconfiguration-restart-kubelet.yaml
This PR introduces several important updates:
1. **New CSI Driver Provisioner**: Added the creation of a CSI driver resource with the new provisioner.
2. **Remove Old CSI Driver**: Implemented the removal of the CSI driver resource associated with the old provisioner.
3. **Additional Kubelet Restart**: Added a second restart of the kubelet 180 seconds after the first. This additional restart addresses an issue where some pods, particularly those using PVCs with the migrating provisioner, would get stuck in a `Terminating` state due to unmount errors if only one restart was performed.
- Successful creation of the new CSI driver resource.
- Complete removal of the old CSI driver resource.
- Elimination of issues with pods getting stuck in `Terminating` state due to unmount errors, thanks to …
=> [controller] Add resource CSIDriver with new provisioner, remove resource CSIDriver with old provisioner, and implement additional kubelet restart

openapi/config-values.yaml, templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml, templates/nodegroupconfiguration-drbd-install-centos-like.yaml, templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Remove deprecated registryScheme parameter
Correct work with registry from ModuleSource resource without external workarounds
=> [bashible] remove deprecated registryScheme parameter

monitoring/prometheus-rules/linstor-backup.yaml
There can be obsolete secrets with LINSTOR metadata backups in clusters
No obsolete secrets in clusters
=> [monitoring] Add alert about obsolete LINSTOR metadata backups

images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool.go
Fixed a bug when Linstor API's not found error type was handled by kubernetes api errors lib.
Correct linstor not found error handling.
Correct linstor not found error handling.
=> [controller] Fix a bug with wrong not found error lib

enabled
Fix enable script in sds-drbd module
In some cases there is possible, that sds-drbd module disable even when sds-node-configurator module enabled
Correct work of sds-drbd module
=> [internal] Fix enabled script

images/service-scripts/tools/evict.sh, images/service-scripts/werf.inc.yaml, templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
This PR modifies the `evict.sh` script to respect the `AutoplaceTarget` property. When this property is set to `false`, the script will ensure that resource replicas do not move to such nodes during evacuation. This prevents automatic placement of replicas on nodes that are not intended to host them.
Without this change, replicas could be placed on nodes with `AutoplaceTarget=false`, leading to undesired resource placement. Respecting the `AutoplaceTarget` setting improves control over resource allocation, ensuring that replicas are only moved to appropriate nodes.
- Replicas will not be placed on nodes with the `AutoplaceTarget=false` setting during eviction.
- Improved control over where resources are placed during evacuation processes.
=> [controller] Honor `AutoplaceTarget` property in `evict.sh` script

LICENSE
Adding LICENSE file
It will enable us using https://pkg.go.dev/license-policy
License is present and we are able to see published symbols there: https://pkg.go.dev/github.com/deckhouse/sds-node-configurator/api/v1alpha1
=> [docs] Add LICENSE

hooks/generate_webhook_certs.py, templates/linstor-scheduler-admission/secret.yaml
Secret 'linstor-scheduler-admission-certs' was removed in PR #185 for Deckhouse 1.64+, but it is being recreated by `generate_webhook_certs.py` hook and then deleted by Helm and this behavior happens again and again.
Fix bug described above.
Secret 'linstor-scheduler-admission-certs' should stay 'as is' until most users upgrade to Deckhouse 1.64+ (February 2025?)
=> [scheduler] Fix admission controller secret conflict

monitoring/prometheus-rules/linstor-scheduler-admission.tpl
`linstor-scheduler-admission` does not used (and running) anymore in Deckhouse >= 1.64. 
Remove prometheus alerts from Deckhouse >= 1.64 related to `linstor-scheduler-admission` pods.
This is a fix for PR #185.
=> [monitoring] Fix alerts for LinstorSchedulerAdmission pods

images/sds-replicated-volume-controller/src/go.sum, images/sds-replicated-volume-controller/src/pkg/controller/controller_suite_test.go, images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class.go, images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_class_test.go, images/webhooks/src/go.sum
1. **Add Finalizers to StorageClass**:
- Automatically add finalizers to `StorageClass` entities with the provisioner `replicated.csi.storage.deckhouse.io` when they are created. This ensures that these `StorageClass` objects cannot be deleted by users directly.
2. **Check Finalizers on Delete**:
- Implement checks for finalizers when a `StorageClass` is requested to be deleted. This will prevent the deletion of `StorageClass` entities with the specified provisioner until the finalizers are properly handled.
3. **Fix Tests**:
- Update existing tests and add new tests to cover the changes related to adding and checking finalizers on `StorageClass`.
During the migration from the internal module linstor to sds-replicated-volume, we decided to allow users to delete StorageClass. After the …
=> [controller] Add finalizers to StorageClass

images/sds-replicated-volume-controller/src/pkg/controller/linstor_resources_watcher.go, monitoring/prometheus-rules/replicated-pv-with-incorrect-settings.yaml
Added verification of minimal PV Resources Volumes count (required number of replicas stored in the StorageClass)
We will be alerted if there are problems with the number of PV resources
New alerts have been added to Prometheus. With different log and severity levels
log_level: Warning, Error, Fatal
severity_level: S4, S5, S6
alert_name: **ReplicatedPVIncorrectReplicasCount<log_level><severity_level>**
=> [monitoring] Check pv minimum count

templates/linstor-scheduler/deployment.yaml, templates/linstor-scheduler/kube-scheduler-webhook-configuration.yaml, templates/linstor-scheduler/service.yaml, templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml, templates/nodegroupconfiguration-drbd-install-centos-like.yaml, templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Fix for module templates of sds-replicated-volume
Fixed the following error during deploy of Deckhouse with `dev-v1.67-istio-extrafix` tag:
```
ModuleRun failed in phase 'CanRunHelm'. Requeue task to retry after delay. Failed count is 8. Error: template: sds-replicated-volume/templates/nodegroupconfiguration-drbd-install-debian-like.yaml:48:58: executing "sds-replicated-volume/templates/nodegroupconfiguration-drbd-install-debian-like.yaml" at <semverCompare ">=1.58" .Values.global.deckhouseVersion>: error calling semverCompare: Invalid Semantic Version
```
=> dev in tag fix

templates/linstor-csi/controller.yaml, templates/linstor-csi/rbac-for-us.yaml
Add a separate ServiceAccount for the csi-node.
Fix the csi-node pods startup after adding the [Deckhouse hook](https://github.com/deckhouse/deckhouse/blob/b2e60c1d9020a7366c214795dbc9d05ed7717316/modules/002-deckhouse/hooks/disable_sa_token_automount.go). 
Ensure the csi-node pods start successfully.
=> [csi] Add a separate ServiceAccount for the csi-node

images/sds-replicated-volume-controller/pkg/controller/linstor_resources_watcher.go, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
Linstor Resource Definition property 'DrbdOptions/Resource/quorum' set to 'off' on restart
sds-replicated-volume-controller watcher check property and set to 'majority' if needed
=> [controller] Bug fix quorum on controller restart

images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
Because of changes in CSI, we need to add RSC parameter in StorageClasses. So our controller must handle with this.
Correct StorageClasses recreation
=> [controller] Fix RSC recreation

monitoring/prometheus-rules/memory-leak.yaml
D8NodeHighUnknownMemoryUsage alert added
Added alert about high kernel memory usage (it may be caused by DRBD memory leak)
We need more data to investigate and fix it.
=> D8NodeHighUnknownMemoryUsage alert added

monitoring/prometheus-rules/memory-leak.yaml
Fix alert grouping problem
Correct memory alerting
=> [monitoring] Fix D8NodeHighUnknownMemoryUsage alert grouping

templates/sds-replicated-volume-controller/deployment.yaml
We have incorrect sds-replicated-volume-controller podAntiAffinity rules and replicas count
Correct deploy rules
=> Fix sds-replicated-volume-controller podAntiAffinity

.dmtlint.yaml, templates/linstor-controller/deployment.yaml, templates/linstor-node/daemonset.yaml
Add kube-rbac-proxy liveness/readyness probes
Correct module templates
=> [internal] add kube-rbac-proxy liveness/readyness probes

.dmtlint.yaml, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go, images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class_test.go, templates/csi/controller.yaml
Add volumesnapshtoclassname annotation and csi-node name fix
Correct volume snapshot work
=> [internal] add volumesnapshtoclassname annotation and csi-node name fix
