deckhouse/sds-replicated-volume

- templates/linstor-node/daemonset.yaml
Fixed default container in linstor-node satellite pod
> [linstor-node] Fixed default container in linstor-node satellite pod

- .github/ISSUE_TEMPLATE /bug_report.yml
- .github/ISSUE_TEMPLATE /config.yml
- .github/ISSUE_TEMPLATE /feature_request.yml
Added 3 templates for issue.
Improve documetation.
Reduce time for creating new issues.
> [docs] Add issue templates.

- .github/workflows/checks.yaml
Added automation to check if any label is assined to new PR
This check prevents to create PR without any label
Every PR should have at least one assined label
> [ci] Add check if any label is assined to new PR.

- images/linstor-server/client-wrapper.sh
Add help section to console wrapper
More obvious usage of console wrapper
Add help section to console wrapper
> [linstor] Add help section to console wrapper.

- docs/FAQ.md
- docs/LAYOUTS.md
- docs/README.md
- docs/USAGE.md
The following files have been translated:
- README.md
- LAYOUTS.md
- FAQ.md
- USAGE.md
This PR aligns the Russian and English versions of the documentation.
> Translate sds-drbd docs to reflect changes in RU versions

- .github/workflows/checks.yaml
Add label documentation in checks.yaml
Without this fix PR check with label documentation fails
Fix errors during check
> [docs] Add label documentation in checks.yaml

- templates/webhooks/webhook.yaml
Changed webhooks names, so there will be more obvious, which module they belongs.
Not obvious names
More obvious names
> [controller] Change webhook names to more obvious ones

- images/sds-drbd-controller/pkg/controller/drbd_storage_class.go
- images/sds-drbd-controller/pkg/controller/drbd_storage_class_test.go
Now if DRBDStorageClass has isDefault flag (after update or create operation) the controller will check if any of DRBDStorageClass resources or Storage Classes have already have the isDefault annotation.
This prevents several default DRBDStorageClasses or Storage Classes existence in a cluster.
If a user tries to make a DRBDStorageClass as default while there is a default DRBDStorageClass or StorageClass in a cluster, the validation of the resource will fail.
> [controller] Change DRBDStorageClass isDefault validation logic

- crds/replicatedstoragepool.yaml
- enabled
- hooks/initial_backup.py
- hooks/migrate_sdsdrbd_crds.py
- images/sds-replicated-volume-controller/api/v1alpha1/replicated_storage_pool.go
- Changes in the enabled script to verify that the linstor and sds-drbd modules are disabled 
- Added migration of DRBD* resources to Replicated* 
- Changes into the linstor database backup script.
This is preparation for sds-drbd to sds-replicated-volume migration
Successful migration from sds-drbd to sds-replicated-volume
> Preparing for migration from sds-drbd to sds-replicated-volume

- monitoring/prometheus-rules/linstor-storage-pools.yaml
> [monitoring] Add new alerts about free storage pool capacity

- images/webhooks/src/main.go
- images/webhooks/src/validators/rscValidator.go
Fix webhook topology check
Ignored topology  must be set in clusters without zones
Correctly working webhook
> [controller] Fix webhook topology check

- templates/linstor-csi/controller.yaml
- templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Fix node selector for DaemonSet and NGC
Now we have partly incorrect node selector
Correct node selector
> Fix node selector for DaemonSet and NGC

- templates/linstor-csi/controller.yaml
- templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Fix node selector for DaemonSet and NGC
Now we have partly incorrect node selector
Correct node selector
> Fix node selector for DaemonSet and NGC (fix for sds-drbd module)

- crds/doc-ru-replicatedstoragepool.yaml
Changed lvmvolumegroups to lvmVolumeGroups in russian docs
This is typo in docs
Correct docs
> [docs] Changed lvmvolumegroups to lvmVolumeGroups in russian docs

- docs/CONFIGURATION.md
- docs/CONFIGURATION_RU.md
- docs/CR.md
- docs/CR_RU.md
- docs/FAQ.md
- docs/FAQ_RU.md
- docs/LAYOUTS.md
- docs/LAYOUTS_RU.md
- docs/README.md
- docs/README_RU.md
- docs/USAGE.md
- docs/USAGE_RU.md
Add deprecation message
Module is deprecated and not longer supported
Deprecation warning in documentation
> [docs] Add deprecation message

- monitoring/prometheus-rules/storage-class.yaml
Fix nonoperational storage class alert
Now alert covers not all possible labels
Correct monitoring work
> [monitoring] Fix nonoperational storage class alert

- images/drbd-reactor/Dockerfile
- images/drbd/werf.inc.yaml
- images/linstor-server/Dockerfile
- images/spaas/Dockerfile
- images/spaas/patches/add_checksum.patch
- openapi/values.yaml
- templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Update DRBD to 9.2.9
New version contains multiple problem fixes
[Fix](https://github.com/LINBIT/drbd/releases/tag/drbd-9.2.9) multiple old problems (mostly unexpected reboots in different situations)
> [DRBD] Update DRBD to 9.2.9

- docs/README.md
- docs/README_RU.md
Change the module status from `experimental` to `preview`.
The status of the module in the documentation is `preview`.
> [docs] Change the module status to preview

- templates/linstor-csi/controller.yaml
Add severity level on CSI plugin
We need more info in debug cases
More info in debug cases
> [linstor] Add severity level on CSI plugin

- templates/sds-replicated-volume-controller/deployment.yaml
Add controller's pods antiaffinity rules
We need to use different nodes while HA mode is switch on
Working antiaffinity rules
> [controller] add pod antiaffinity rules

- monitoring/grafana-dashboards/storage/linstor_drbd.json
Fix in dashboard
Actual dashboard
> [monitoring] fix in dashboard

- images/linstor-server/client-wrapper.sh
- monitoring/prometheus-rules/linstor-storage-pools.yaml
Fix free space alerts
Actual free space alerts
> [monitoring] fix free space alerts

- templates/webhooks/deployment.yaml
Fix webhook template
We have problems in webhook template
Working webhook
> [internal] fix webhook template

- images/sds-replicated-volume-controller/cmd/main.go
- images/sds-replicated-volume-controller/config/config.go
- templates/sds-replicated-volume-controller/deployment.yaml
Add liveness and readiness checks to controller
Correct checks of deployment
> [controller] add liveness and readiness checks

- images/sds-replicated-volume-controller/cmd/main.go
We have error occured due the refactoring
Working module
> Fix in register func

- monitoring/grafana-dashboards/storage/linstor_drbd.json
Add table with DRBD versions
Information about DRBD versions in Grafana dashboard
> [monitoring] Add table with DRBD versions

- templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Old method is deprecated, we needs to switch ASAP
Working module NGC
> [controller] Switch to bb-package-module-install in NGC

- docs/FAQ.md
- docs/FAQ_RU.md
Fixes in FAQ about node eviction and resources move
Correct docs
> [docs] Fixes in FAQ about node eviction and resources move

- images/sds-replicated-volume-controller/pkg/controller/replicated_storage_class.go
Some improvements in controller logging
More information in logs
> [controller] Improve logging

- images/metadata-backup/backup.py
In backup there is no check for backup name in metadata object
Working backup
> [controller] Small fix in backup

- images/sds-replicated-volume-controller/src/go.mod
- images/sds-replicated-volume-controller/src/go.sum
- images/sds-replicated-volume-controller/werf.inc.yaml
- images/webhooks/src/go.mod
- images/webhooks/werf.inc.yaml
Updated sds-node-configurator and sds-replicated-volume api versions.
Consistent data.
Works fine.
> [controller] Update api models versions.

- docs/README.md
- docs/README_RU.md
Small fixes in installation process description
Actual documentation
> [docs] Small fixes in installation process description

- templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- templates/nodegroupconfiguration-drbd-install-debian-like.yaml
- templates/nodegroupconfiguration-restart-kubelet.yaml
While using `hostname -s` we can have problem if node hostname contains dots
Correct bashible steps work
> [bashible] changes in NodeGroupConfigurations to correct label query

- .github/workflows/trivy_check.yaml
- .github/workflows/trivy_image_check.yaml
- lib/python/requirements.txt
- trivy-silent.yaml
- trivy.yaml
Add Trivy vulnerables check (also fixes one vulnerable in go code)
Modules without known vulnerables
> [CI] Add Trivy vulnerables check

- .github/workflows/trivy_check.yaml
- .werf/images-digests.yaml
- images/drbd-reactor/Dockerfile
- images/linstor-affinity-controller/Dockerfile
- images/linstor-csi/Dockerfile
- images/linstor-drbd-wait/Dockerfile
- images/linstor-scheduler-admission/Dockerfile
- images/linstor-scheduler-extender/Dockerfile
- images/linstor-server/Dockerfile
- images/linstor-wait-until/Dockerfile
- images/metadata-backup/werf.inc.yaml
- images/spaas/Dockerfile
Fixes in CI and update of base ubuntu image to fix some known vulnerabilites
More secure images
> [CI] fixes in build and CI

- docs/README.md
- docs/README_RU.md
Small fixes in documentation links
Correct documentation
> [docs] Small docs fixes

- images/sds-replicated-volume-controller/src/pkg/controller/linstor_node.go
This PR resolves an issue where the reconciliation process for topology keys would fail with an error if a CSI node existed without the `replicated.csi.storage.deckhouse.io` driver. The reconciliation logic now skips nodes without the required driver, preventing these errors and ensuring that the process only runs on applicable nodes.
Previously, the reconciliation process would fail on nodes without the `replicated.csi.storage.deckhouse.io` driver, causing errors. This fix ensures that the reconciliation process only occurs on nodes with the relevant driver, preventing unnecessary failures and improving system stability.
- Topology key reconciliation will only occur on nodes with the `replicated.csi.storage.deckhouse.io` driver.
- Errors related to missing drivers on nodes will no longer …
> [controller] Fix CSI node topology keys reconciliation error

- api/v1alpha1/replicated_storage_pool.go
- docs/README.md
- docs/README_RU.md
- images/sds-replicated-volume-controller/src/go.mod
- images/sds-replicated-volume-controller/src/go.sum
- images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool.go
- images/sds-replicated-volume-controller/src/pkg/controller/replicated_storage_pool_test.go
- images/webhooks/src/go.mod
- images/webhooks/src/go.sum
- images/webhooks/src/handlers/rspValidator.go
Updated version for sds-node-configurator api module.
Consistent and working code.
Everything works fine.
> [controller] Update sds-node-configuration api version

- crds/replicatedstoragebackup.yaml
- crds/replicatedstorageclass.yaml
- crds/replicatedstoragepool.yaml
We need to backup our CRs
Our internal backup mechanism needs label on CRD to recognize it
Correct backup work
> [internal] Add backup control label

- monitoring/prometheus-rules/replicated-pv-with-incorrect-settings.yaml
Fix incorrect replicas alert description
Correct instruction for users about actions
> [monitoring] Fix incorrect replicas alert description

- templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- templates/nodegroupconfiguration-drbd-install-debian-like.yaml
There can be situation where ngc tries to use semver before it setup
Correct ngc work
> [internal] add semver installation in ngc

- .werf/consts.yaml
- openapi/values.yaml
New release 9.2.13 fixes some problems, that caused because of 9.2.12 release, also correct DRBD build on new OS kernels
Correct  DRBD build and work
> [internal] update drbd to 9.2.13

- images/linstor-csi/werf.inc.yaml
Fix the linstor-csi image build.
The linstor-csi image is building without errors.
> Fix werf linstor-csi

- images/sds-replicated-volume-controller/pkg/controller/storage_class_annotations_test.go
* Remove code duplication in test
* Updates test by new design
> [controller] Make tests pass

- docs/README.md
- docs/README_RU.md
Add snapshot-controller requirement info
Correct documentation
> [internal] add snapshot-controller requirement info
